### ISSUE TITLE
Importing CSV fails when column is set as "Existing field as identifier" and rows are empty

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#271]
Found in version 1.2-pre1

1. Open an application and navigate to Data
2. Create new data from CSV and select a CSV that has an ID column with numeric fields
2. Click on 'Import CSV' to update the table with new records
3. Select a CSV that has an id column with some empty fields 
4. Add a name and click the 'Import' button

NOTE: same happens if the fields have letters instead of being empty.

Obtained: 500 error page and error
```
Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[8bDquHipSDOf38PxkISVxw][mbuilder_application_175][0]: SearchParseException[[mbuilder_application_175][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"match\":{\"4793ded5-2cd0-3a32-71e2-78e18cfe5a9f\":{\"query\":\"\"}}},\"size\":10}]]]; nested: NumberFormatException[empty String]; }]","status":400}):
 app/elastic_record/elastic_query.rb:190:in `initialize_results'
 app/elastic_record/elastic_query.rb:139:in `results'
 app/elastic_record/elastic_query.rb:78:in `each'
 app/models/tables/importer.rb:71:in `to_a'
 app/models/tables/importer.rb:71:in `find_table_record'
 app/models/tables/importer.rb:127:in `block in execute!'
 app/models/tables/importer.rb:125:in `each'
 app/models/tables/importer.rb:125:in `execute!'
 app/controllers/tables_controller.rb:22:in `import'

```
Expected: the rows with empty fields fail but the rest of the CSV is uploaded successfully.

**Comment by pmallol** [comment]
Ok in version 1.2-pre2
